/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_taoweiji_nativemodule_NativeDemo */

#ifndef _Included_cn_taoweiji_nativemodule_NativeDemo
#define _Included_cn_taoweiji_nativemodule_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_taoweiji_nativemodule_NativeDemo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_taoweiji_nativemodule_NativeDemo_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_taoweiji_nativemodule_NativeDemo
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_taoweiji_nativemodule_NativeDemo_say
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_taoweiji_nativemodule_NativeDemo
 * Method:    getInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_taoweiji_nativemodule_NativeDemo_getInfo
  (JNIEnv *, jclass);

/*
 * Class:     cn_taoweiji_nativemodule_NativeDemo
 * Method:    nativeToJava
 * Signature: (Lcn/taoweiji/nativemodule/NativeDemo;)V
 */
JNIEXPORT void JNICALL Java_cn_taoweiji_nativemodule_NativeDemo_nativeToJava
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
